### ISSUE TITLE
Dataset used and model performance

### ISSUE THREAD

**Issue by caolingyu** [Tian312/PICO_Parser#1]
Hi Tian,

I'm interested in your work and have some questions. 
- Did you use PubMed abstracts to train the model? if so, how large is it?
- Could you provide performance of model on your test data, such as f1 score?

Thanks a lot in advance.

**Comment by Tian312** [comment]
Hi conglingyu,

Thanks for your interests. We pretrained our model on a large dataset of PubMed abstracts and then fine tuned with our own annotation with PICO. Because this is still a nundergoing project, we will release the results once is finished. 

Tian
