### ISSUE TITLE
Could you please share 170 annotated publications?

### ISSUE THREAD

**Issue by tutubalinaev** [Tian312/PICO_Parser#2]
Hi,

Could you please share 170 annotated publications? https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6852618/

Best regards,
Elena

**Comment by Tian312** [comment]
Hi @tutubalinaev, thank you for your interests in this project. Since this is in one part of our ongoing project, we haven't released the dataset to the public yet. We plan to share the datasets including both this and ongoing ones later. Sorry for the inconvenience.
