### ISSUE TITLE
Context vector download link broken

### ISSUE THREAD

**Issue by cephcyn** [Tian312/PICO_Parser#4]
In your documentation for LSTM parser you mention that `LSTM_Parser/cluster/model/download.txt` contains a link for the context vector download. This download link is broken:

https://drive.google.com/open?id=1Qs0--7eX9dMq4ngQQRpG_VnYGygGdIaF

Is there another download link that would work? Thanks!

**Comment by Tian312** [comment]
link updated. https://drive.google.com/open?id=1wip5FvNbvy1bU0_u73aL3BjTpFPHlroL
