### ISSUE TITLE
Model evaluation

### ISSUE THREAD

**Issue by miladnouriezade** [Tian312/PICO_Parser#5]
Hi, I've tried to evaluate your model with scibert pico data set, but the tokenization wasn't the same, could you please share the F1 score you get?

**Comment by Tian312** [comment]
Hi @miladnouriezade. Thank you for your interests. The performance of a part of the entity classes including PICO is listed below (note that we have a new set of attribute categories for PICO and delete the original "modifier" and "measure". we will release our new version in the future):  
```
Intervention: precision:  69.14%; recall:  73.68%; FB1:  71.34 
Observation: precision:  70.54%; recall:  80.53%; FB1:  75.21  
Outcome: precision:  71.51%; recall:  78.85%; FB1:  75.00  
Participant: precision:  58.11%; recall:  70.49%; FB1:  63.70 
```
